# Batch 1: First 15 recipes
import pandas as pd
import os

recipes = [
    # name, category, meal_type, food_type, food_group, difficulty, cook_time_mins, calories, protein, carbohydrate, fat, portion_min, portion_typical, portion_max, role, cuisine, description, tags, source
    ["Set Dosa", "recipe", "Breakfast", "veg", "south_indian", "Easy", 20, 234, 4.2, 38.0, 6.5, 0.5, 1.0, 1.5, "complete_meal", "indian", "Soft, spongy South Indian dosa served in a set of three. Made from fermented rice and urad dal batter, these thick, pillowy dosas are lightly crisp on the outside and airy inside. A comforting breakfast staple from Karnataka, typically served with coconut chutney and vegetable sagu.", "south indian breakfast;soft dosa;fermented batter;comfort food;traditional", "https://www.indianhealthyrecipes.com/set-dosa-recipe/", "3 dosas (~180g)", "Rice 60g|Urad dal 20g|Fenugreek seeds 2g|Poha 15g|Oil 10ml|Salt to taste", "Wash and soak rice, dal and fenugreek separately for 4 hours|Grind to smooth batter; mix with soaked poha; ferment overnight|Add salt; heat tawa; pour ladleful of thick batter; spread gently|Cover and cook 2 min; flip; cook 1 min more; serve hot with chutney"],
    ["Dahi Puri", "recipe", "Snack", "veg", "chaat", "Easy", 15, 367, 7.4, 29.8, 22.1, 0.5, 1.0, 1.5, "complete_meal", "indian", "A beloved Mumbai street food chaat featuring crispy semolina puris filled with boiled potatoes, sprouted moong, chilled sweetened yoghurt, tangy tamarind chutney and fresh coriander. Each bite delivers a burst of sweet, sour, spicy and creamy flavours in perfect harmony.", "mumbai street food;chaat favourite;sweet and tangy;crispy puri;yoghurt based", "https://www.tarladalal.com/calories-for-dahi-puri-2807", "1 plate (~200g)", "Semolina puris 8 pieces|Potato 80g|Sprouted moong 40g|Yoghurt 100g|Tamarind chutney 20g|Green chutney 15g|Chaat masala 2g|Sev 10g|Coriander 5g", "Crisp puris are arranged on a plate; crack a hole in each|Stuff with mashed potato and sprouted moong|Pour chilled sweetened yoghurt over each puri|Drizzle tamarind and green chutney|Sprinkle chaat masala, sev and coriander; serve immediately"],
    ["Rava Idli", "recipe", "Breakfast", "veg", "south_indian", "Easy", 20, 150, 5.0, 17.0, 6.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "Fluffy, instant steamed cakes made from roasted semolina, tempered with mustard seeds, curry leaves and cashews. Unlike traditional rice idlis, these require no grinding or overnight fermentation, making them a quick yet nutritious South Indian breakfast option.", "instant breakfast;semolina idli;steamed cake;south indian;quick recipe", "https://www.indianhealthyrecipes.com/rava-idli-recipe/", "4 idlis (~200g)", "Semolina 80g|Yoghurt 60g|Water 40ml|Carrot 20g|Cashews 10g|Oil 10ml|Mustard seeds 2g|Curry leaves 4|Baking soda 1g|Salt to taste", "Dry roast semolina until fragrant; cool|Mix with yoghurt, water, grated carrot and salt; rest 30 min|Temper mustard seeds, curry leaves, cashews in oil; add to batter|Add baking soda; mix gently; pour into greased idli moulds|Steam 10 min; cool 2 min; demould and serve with chutney"],
    ["Neer Dosa", "recipe", "Breakfast", "veg", "south_indian", "Easy", 15, 120, 1.8, 24.0, 1.5, 0.5, 1.0, 1.5, "complete_meal", "indian", "A thin, watery rice batter pancake from coastal Karnataka, neer dosa is delicate, soft and almost translucent. The name translates to water dosa, referring to the runny consistency of the batter. It pairs beautifully with coconut chutney, sagu or chicken curry.", "coastal karnataka;thin pancake;water dosa;soft texture;rice based", "https://www.fatsecret.co.in/calories-nutrition/search?q=Neer+Dosa", "2 dosas (~150g)", "Rice 80g|Coconut grated 15g|Water 150ml|Salt to taste|Oil 5ml", "Soak rice for 4 hours; drain|Grind with coconut, water and salt to thin watery batter|Heat non-stick tawa; pour a ladleful; swirl to spread thin|Cook 1 min; fold; serve hot with chutney or curry"],
    ["Wheat Dosa", "recipe", "Breakfast", "veg", "south_indian", "Easy", 15, 180, 4.5, 32.0, 3.5, 0.5, 1.0, 1.5, "complete_meal", "indian", "A wholesome alternative to rice dosas, this instant dosa uses whole wheat flour blended with buttermilk and spices. The result is a slightly tangy, aromatic crepe that cooks quickly and provides more fibre than traditional rice-based varieties.", "instant dosa;whole wheat;high fibre;quick breakfast;tangy flavour", "https://www.tarladalal.com/calories-for-wheat-dosa-2807", "2 dosas (~160g)", "Wheat flour 80g|Buttermilk 120ml|Onion 30g|Green chilli 1|Cumin seeds 2g|Oil 10ml|Salt to taste", "Mix wheat flour with buttermilk, salt and water to thin batter|Add chopped onion, green chilli and cumin|Heat tawa; pour batter; spread thin|Drizzle oil; cook 1 min; flip; cook 30 sec; serve hot"],
    ["Tomato Uttapam", "recipe", "Breakfast", "veg", "south_indian", "Easy", 20, 200, 4.0, 34.0, 5.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "A thick, savoury pancake topped with juicy tomato slices, onion and green chillies. Unlike the thin dosa, uttapam is fluffy and bread-like with toppings embedded into the batter. The tomatoes caramelise slightly on the hot griddle, adding a sweet-savoury depth.", "thick pancake;tomato topping;south indian;fluffy texture;caramelised", "https://www.tarladalal.com/calories-for-tomato-uttapam-2807", "1 uttapam (~180g)", "Rice 60g|Urad dal 20g|Tomato 60g|Onion 30g|Green chilli 1|Oil 10ml|Salt to taste", "Soak rice and dal 4 hours; grind to thick batter; ferment overnight|Slice tomato and onion thinly|Heat tawa; pour thick batter; do not spread too thin|Top with tomato, onion, green chilli and salt|Drizzle oil; cover; cook 3 min; flip; cook 2 min; serve"],
    ["Adai", "recipe", "Breakfast", "vegan", "south_indian", "Medium", 30, 280, 8.0, 42.0, 8.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "A protein-rich mixed lentil dosa from Tamil Nadu, adai combines rice with chana dal, moong dal and toor dal. The batter is coarsely ground, giving the dosa a hearty, grainy texture. It is traditionally served with avial, a mixed vegetable coconut curry.", "mixed lentil;protein rich;coarse texture;tamil nadu;hearty breakfast", "https://www.tarladalal.com/calories-for-adai-2807", "2 adai (~200g)", "Rice 40g|Chana dal 20g|Moong dal 15g|Toor dal 15g|Red chilli 2|Asafoetida 1g|Oil 15ml|Salt to taste", "Soak rice and all dals together for 3 hours|Drain; grind with red chilli and asafoetida to coarse thick batter|Add salt; mix well|Heat tawa; pour ladleful; spread thick|Make a small hole in centre; pour oil; cook covered 3 min|Flip; cook 2 min; serve with avial or jaggery"],
    ["Kuzhi Paniyaram", "recipe", "Breakfast", "veg", "south_indian", "Medium", 25, 240, 5.0, 38.0, 7.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "Small, round, golden-fried dumplings cooked in a special cast-iron pan with hemispherical moulds. Made from fermented idli batter tempered with mustard seeds, curry leaves and onion, they are crispy outside and soft inside. A popular Tamil Nadu breakfast and tea-time snack.", "crispy dumplings;fermented batter;special pan;tea time snack;tamil nadu", "https://www.tarladalal.com/calories-for-kuzhi-paniyaram-2807", "8 paniyaram (~200g)", "Rice 60g|Urad dal 20g|Onion 40g|Green chilli 1|Mustard seeds 2g|Curry leaves 4|Oil 15ml|Salt to taste", "Soak rice and dal 4 hours; grind; ferment overnight|Make tempering with mustard, curry leaves, onion and chilli|Mix into batter|Heat paniyaram pan; add oil to each mould|Pour batter; cook 3 min; turn each with skewer; cook 2 min more"],
    ["Puttu", "recipe", "Breakfast", "vegan", "south_indian", "Easy", 20, 220, 4.0, 40.0, 4.5, 0.5, 1.0, 1.5, "complete_meal", "indian", "A cylindrical steamed cake of layered rice flour and grated coconut, puttu is Kerala's signature breakfast. Cooked in a special puttu maker, the resulting texture is light, crumbly and fragrant. It is traditionally served with kadala curry, a spiced black chickpea stew.", "kerala breakfast;steamed cake;cylindrical shape;crumbly texture;coconut", "https://www.tarladalal.com/calories-for-puttu-2807", "1 cylinder (~180g)", "Rice flour 100g|Grated coconut 30g|Water 60ml|Salt to taste", "Mix rice flour with salt; sprinkle water gradually until crumbly|Layer rice flour and coconut in puttu maker|Steam 10-15 min until cooked through|Push out gently; serve hot with kadala curry or banana"],
    ["Appam", "recipe", "Breakfast", "vegan", "south_indian", "Medium", 25, 150, 2.5, 28.0, 3.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "A soft, bowl-shaped rice pancake with a lacy, crispy edge and fluffy centre. The batter is fermented with yeast or toddy, giving appam a subtle tang and airy texture. It is a staple breakfast in Kerala and Sri Lanka, best enjoyed with vegetable stew or egg curry.", "bowl shaped;lacy edges;fermented batter;kerala staple;airy texture", "https://www.tarladalal.com/calories-for-appam-2807", "2 appams (~160g)", "Rice 80g|Coconut milk 40ml|Yeast 1g|Sugar 5g|Salt to taste|Oil 5ml", "Soak rice 4 hours; grind with coconut milk to smooth batter|Add yeast, sugar and salt; ferment 6-8 hours|Heat appam pan; pour ladleful; swirl to coat sides|Cover; cook 2 min until edges are lacy and centre fluffy|Serve with stew or curry"],
    ["Nei Appam", "recipe", "Breakfast", "veg", "south_indian", "Medium", 30, 200, 3.0, 30.0, 7.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "Sweet, deep-fried rice fritters made with jaggery, banana and ghee. Nei appam has a crisp, caramelised exterior and a soft, moist interior with warm notes of cardamom. Traditionally prepared during festivals like Vishu and Krishna Jayanti in Kerala and Tamil Nadu.", "sweet fritter;jaggery sweetened;festival special;crisp exterior;kerala sweet", "https://www.tarladalal.com/calories-for-nei-appam-2807", "5 appams (~150g)", "Rice flour 80g|Jaggery 40g|Banana 30g|Ghee 15ml|Cardamom powder 1g|Oil for frying 10ml", "Melt jaggery in water; strain; cool|Mix with rice flour, mashed banana, cardamom and ghee to thick batter|Heat paniyaram pan with ghee in each mould|Pour batter; cook 2 min; flip; cook 1 min|Drain; serve warm"],
    ["Mysore Bonda", "recipe", "Breakfast", "veg", "south_indian", "Medium", 25, 280, 6.0, 32.0, 14.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "Crispy, golden-brown fritters made from urad dal batter flavoured with cumin, pepper and curry leaves. Mysore bonda is a popular Karnataka breakfast and tea-time snack, known for its airy, doughnut-like interior and fragrant, crunchy crust.", "crispy fritter;urad dal based;tea time snack;karnataka special;golden brown", "https://www.tarladalal.com/calories-for-mysore-bonda-2807", "4 bondas (~160g)", "Urad dal 80g|Rice flour 10g|Green chilli 1|Ginger 5g|Cumin seeds 2g|Peppercorns 2g|Curry leaves 4|Oil for frying 15ml|Salt to taste", "Soak urad dal 4 hours; drain; grind to fluffy batter with minimal water|Add rice flour, chopped chilli, ginger, cumin, pepper and curry leaves|Heat oil; wet hands; shape batter into round balls|Deep fry on medium heat until golden and crisp|Drain; serve hot with coconut chutney"],
    ["Maddur Vada", "recipe", "Breakfast", "veg", "south_indian", "Medium", 25, 260, 5.0, 28.0, 14.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "A signature savoury fritter from Maddur, Karnataka, made with a mix of rice flour, semolina and all-purpose flour. It is flattened before frying, giving it a unique disc shape with a crisp edge and soft centre. The flavour is mildly spiced with onion and cumin.", "disc shaped;mixed flour;karnataka special;crisp edge;savoury fritter", "https://www.tarladalal.com/calories-for-maddur-vada-2807", "2 vadas (~120g)", "Rice flour 40g|Semolina 30g|Maida 20g|Onion 30g|Cumin seeds 2g|Green chilli 1|Oil for frying 15ml|Salt to taste", "Mix all flours with chopped onion, chilli, cumin and salt|Add water to form stiff dough|Divide; flatten into discs|Deep fry on medium heat until golden and crisp|Drain; serve hot"],
    ["Thalipeeth", "recipe", "Breakfast", "veg", "grain_breakfast", "Medium", 25, 240, 6.0, 38.0, 7.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "A rustic, multi-grain flatbread from Maharashtra, thalipeeth is made from a special flour mix called bhajani that includes wheat, rice, bajra, jowar and urad dal. The dough is pressed by hand into a thin, uneven disc and cooked with a hole in the centre for oil.", "multi grain;maharashtra special;hand pressed;rustic flatbread;bhajani flour", "https://www.tarladalal.com/calories-for-thalipeeth-2807", "1 thalipeeth (~150g)", "Wheat flour 30g|Rice flour 20g|Bajra flour 20g|Jowar flour 20g|Urad dal flour 10g|Onion 30g|Coriander 10g|Cumin seeds 2g|Oil 15ml|Salt to taste", "Mix all flours with onion, coriander, cumin and salt|Add water to stiff dough|Place dough on hot tawa; press by hand into thin flatbread|Make a small hole in centre; pour oil|Cook covered 3 min; flip; cook 2 min; serve with curd or pickle"],
    ["Sabudana Vada", "recipe", "Breakfast", "veg", "grain_breakfast", "Medium", 30, 280, 3.0, 38.0, 12.0, 0.5, 1.0, 1.5, "complete_meal", "indian", "Crispy, deep-fried patties made from soaked tapioca pearls, mashed potatoes and crushed peanuts. Sabudana vada is a popular fasting food and breakfast across Maharashtra and Gujarat, prized for its crunchy exterior and soft, starchy interior with nutty peanut notes.", "crispy patty;tapioca pearls;fasting food;peanut crunch;maharashtra snack", "https://www.tarladalal.com/calories-for-sabudana-vada-2807", "3 vadas (~150g)", "Sabudana 80g|Potato 60g|Peanuts 20g|Green chilli 1|Cumin seeds 2g|Oil for frying 15ml|Salt to taste", "Soak sabudana 4 hours; drain well|Boil and mash potato|Crush peanuts coarsely|Mix all ingredients with salt to form dough|Shape into patties|Deep fry on medium heat until golden and crisp|Drain; serve with curd or chutney"],
]

# Split into recipes.csv format and recipe_details.csv format
recipes_df = pd.DataFrame(recipes, columns=[
    "name", "category", "meal_type", "food_type", "food_group", "difficulty",
    "cook_time_mins", "calories", "protein", "carbohydrate", "fat",
    "portion_min", "portion_typical", "portion_max", "role", "cuisine",
    "description", "tags", "source", "serving_note", "ingredients", "steps"
])

# Write recipes
recipes_out = recipes_df[["name", "category", "meal_type", "food_type", "food_group",
                          "difficulty", "cook_time_mins", "calories", "protein",
                          "carbohydrate", "fat", "portion_min", "portion_typical",
                          "portion_max", "role", "cuisine", "description", "tags", "source"]]

# Write details
details_out = recipes_df[["name", "serving_note", "ingredients", "steps"]]

os.makedirs("data", exist_ok=True)

# Check if files exist
if os.path.exists("data/recipes_generated.csv"):
    existing_recipes = pd.read_csv("data/recipes_generated.csv")
    recipes_out = pd.concat([existing_recipes, recipes_out], ignore_index=True)

if os.path.exists("data/recipe_details_generated.csv"):
    existing_details = pd.read_csv("data/recipe_details_generated.csv")
    details_out = pd.concat([existing_details, details_out], ignore_index=True)

recipes_out.to_csv("data/recipes_generated.csv", index=False, encoding="utf-8")
details_out.to_csv("data/recipe_details_generated.csv", index=False, encoding="utf-8")

print(f"Wrote {len(recipes)} recipes. Total in file: {len(recipes_out)}")
